CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_DEVICE=y
CONFIG_INPUT=y
CONFIG_INPUT_MOUSE=y

CONFIG_BT=n
CONFIG_ZMK_BLE=n

CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y
CONFIG_USB_HID=y
CONFIG_ZMK_HID=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_USB=y

CONFIG_SPI=y

CONFIG_GPIO=y
CONFIG_INPUT_GPIO_KEYS=y
